### ISSUE TITLE
Where to host?

### ISSUE THREAD

**Issue by luisivan** [helpdao/donation-backend#2]
We need something that runs NodeJS and MongoDB. [Heroku seems like a good alternative](https://elements.heroku.com/addons/mongolab). Any other ideas?

**Comment by manolingam** [comment]
Heroku would be an option. But the server sleeps after a timeout in their free tier. Maybe we can try a trial run.

**Comment by luisivan** [comment]
Yeah, could do that!

**Comment by luisivan** [comment]
@w0xter what do you think?

**Comment by abkrim** [comment]
What do you needs? I've several machines based on discs NVME with AMD RYZEN EPYC 32 cores... Yesterday mount a machine for miner Etehrum... 
What do you need?

**Comment by luisivan** [comment]
Hey @abkrim! Thanks for offering. I think we will host in some cloud service (Amazon, Heroku) to make sure we have maximum uptime

**Comment by abkrim** [comment]
Ok I 'm enemy of AWS and others... Too many money for smoke... 
I do not know what real need you have for CPU and disk ... but if someone offers you several units with 20vCPU, hundreds of Gb in NVME disks, he is offering you something whose cost on Amazon or Heroku is worth a fortune that should be spent on people which we are going to help and not in companies in which a young community has insisted on using. Stability and 99.99% exist more than the big brands sell fumes.

**Comment by luisivan** [comment]
The AWS people have offered to help and give it all for free, but thanks @abkrim !

**Comment by abkrim** [comment]
Ok. Close
